name: Test action `setup-fastlane`
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup_fastlane:
    name: Install Fastlane
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Setup Fastlane
        uses: ./

      - name: Check Fastlane Command
        run: fastlane --version
